# -*- coding: utf-8 -*-
"""
  run_parameters_init.py generated by WhatsOpt 1.8.2
"""
import numpy as np
from numpy import nan

def initialize(mda):

    mda['a'] = np.ones((32,))
    mda['b'] = np.ones((32,))
    mda['Cf'] = 1.0
    mda['CostAircraft'] = 1.0
    mda['CostRunwayMaint'] = 1.0
    mda['Cox'] = 1.0
    mda['Cp'] = 1.0
    mda['Cpres'] = 1.0
    mda['C_PL'] = 1.0
    mda['DD'] = 1.0
    mda['ExtRunway'] = 1.0
    mda['F'] = 1.0
    mda['f1'] = 1.0
    mda['f10'] = 1.0
    mda['f11'] = 1.0
    mda['f3'] = 1.0
    mda['f8'] = 1.0
    mda['fc'] = 1.0
    mda['fv'] = 1.0
    mda['HoursAircraft'] = 1.0
    mda['HW'] = np.ones((32,))
    mda['I'] = 1.0
    mda['L'] = 1.0
    mda['Launches'] = 1.0
    mda['Ld'] = np.ones((32,))
    mda['LpA'] = 1.0
    mda['M0'] = 1.0
    mda['Mass'] = [25,0,242.6,257,55,2450,0,326,0,0,15,0,312,53.8,10.9,490,0,120,0,0,30,90,45,0,33,0,0,0,0,0,15,20]
    mda['Mp'] = 1.0
    mda['Mpres'] = 1.0
    mda['M_PA_percentage'] = 1.0
    mda['N'] = 1.0
    mda['Ns'] = 1.0
    mda['OnekmRunway'] = 1.0
    mda['P'] = 1.0
    mda['Q_N'] = 1.0
    mda['r'] = 1.0
    mda['S'] = 1.0
    mda['STH'] = 1.0
    mda['Ts'] = 1.0
    mda['W'] = 1.0
    mda['YearsRunway'] = 1.0



if __name__ == "__main__":
    from tabulate import tabulate

    mda = {}
    initialize(mda)
    headers = ["parameter", "value"]
    data = [[k, mda[k]] for k in mda]
    print(tabulate(data, headers))