# -*- coding: utf-8 -*-
"""
  propellant_cost_base.py generated by WhatsOpt 1.8.2
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 322


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class PropellantCostBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate PropellantCost discipline """

    def __init__(self, **kwargs):
        super(PropellantCostBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("propellant_cost")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('Cf', val=15.00, desc='')
        self.add_input('Cox', val=0.45, desc='')
        self.add_input('Cpres', val=50.00, desc='')
        self.add_input('Mp', val=24410.00, desc='')
        self.add_input('Mpres', val=50, desc='')
        self.add_input('r', val=0.12, desc='')

        self.add_output('Cprop', val=1.0, desc='')



        