# -*- coding: utf-8 -*-
"""
  lm_base.py generated by WhatsOpt 1.9.0
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 321


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class LmBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Lm discipline """

    def __init__(self, **kwargs):
        super(LmBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("lm")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('n', val=30, desc='')
        self.add_input('p', val=0.90, desc='')

        self.add_output('Lm', val=1.0, desc='')



        