# -*- coding: utf-8 -*-
"""
  fm1.py generated by WhatsOpt 1.8.2
"""
import numpy as np
from development_cost.fm1_base import Fm1Base

class Fm1(Fm1Base):
    """ An OpenMDAO component to encapsulate Fm1 discipline """
		
    def compute(self, inputs, outputs):
        """ Fm1 computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
            M_PA_percentage = inputs['M_PA_percentage']   
            TFU = inputs['TFU'] 
            FM1 = np.zeros((32,)) # initialisation matrice FM1 de dimension 32,1 avec des zéros

            for i in range(len(TFU)) : # Pour i allant de 0  à 31

                if TFU[i] != 0 : # Si TFU est différent de 0, pas besoin de mettre le cas où TFU = 0 car FM1 initialisé à 0
                    FM1[i] = TFU[i] * (1 - M_PA_percentage) 

            outputs['FM1'] = FM1  
            return outputs

# Reminder: inputs of compute()
#   
#       inputs['M_PA_percentage'] -> shape: 1, type: Float    
#       inputs['TFU'] -> shape: (32,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(Fm1, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Fm1 """
#   
#       	partials['FM1', 'M_PA_percentage'] = np.zeros((32, 1))
#       	partials['FM1', 'TFU'] = np.zeros((32, 32))        
