# -*- coding: utf-8 -*-
"""
  fm1.py generated by WhatsOpt 1.8.2
"""
import numpy as np
from development_cost.fm1_base import Fm1Base

class Fm1(Fm1Base):
    """ An OpenMDAO component to encapsulate Fm1 discipline """
		
    def compute(self, inputs, outputs):
        """ Fm1 computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
                    
            outputs['FM1'] = np.ones((32,))   

# Reminder: inputs of compute()
#   
#       inputs['M_PA_percentage'] -> shape: 1, type: Float    
#       inputs['TFU'] -> shape: 1, type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(Fm1, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Fm1 """
#   
#       	partials['FM1', 'M_PA_percentage'] = np.zeros((32, 1))
#       	partials['FM1', 'TFU'] = np.zeros((32, 1))        
