# -*- coding: utf-8 -*-
"""
  mait_base.py generated by WhatsOpt 1.9.4
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 459


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class MaitBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Mait discipline """

    def __init__(self, **kwargs):
        super(MaitBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("mait")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('FM1', val=np.ones((32,)), desc='')
        self.add_input('HW', val=[1,1,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], desc='Fixé à 1 sauf pour les moteurs')
        self.add_input('Ld', val=[1,1,0.8,1,1,1,1,1,1,1,1,1,0.9,1,1,1,1,1,1,1,1,1,0.5,1,1,1,1,1,1,1,1,1], desc='Courbe d\'apprentissage')
        self.add_input('STH', val=3.10, desc='')

        self.add_output('MAIT', val=np.ones((32,)), desc='')



        