# -*- coding: utf-8 -*-
"""
  mpa.py generated by WhatsOpt 1.9.0
"""
import numpy as np
from development_cost.mpa_base import MpaBase

class Mpa(MpaBase):
    """ An OpenMDAO component to encapsulate Mpa discipline """
		
    def compute(self, inputs, outputs):
        """ Mpa computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
            MAIT = inputs['MAIT'] 
            M_PA_percentage = inputs['M_PA_percentage']
            ENG = inputs ['ENG']

            MPA = (MAIT + ENG) * M_PA_percentage

            outputs['MPA'] = MPA
        return outputs 

# Reminder: inputs of compute()
#   
#       inputs['ENG'] -> shape: 1, type: Float    
#       inputs['MAIT'] -> shape: (32,), type: Float    
#       inputs['M_PA_percentage'] -> shape: 1, type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(Mpa, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Mpa """
#   
#       	partials['MPA', 'ENG'] = np.zeros((32, 1))
#       	partials['MPA', 'MAIT'] = np.zeros((32, 32))
#       	partials['MPA', 'M_PA_percentage'] = np.zeros((32, 1))        
