# -*- coding: utf-8 -*-
"""
  po_base.py generated by WhatsOpt 1.9.4
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 459


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class PoBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Po discipline """

    def __init__(self, **kwargs):
        super(PoBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("po")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('ENG', val=np.ones((32,)), desc='')
        self.add_input('MPA', val=np.ones((32,)), desc='')

        self.add_output('PO', val=np.ones((32,)), desc='')



        