# -*- coding: utf-8 -*-
"""
  tfu_base.py generated by WhatsOpt 1.8.2
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 459


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class TfuBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Tfu discipline """

    def __init__(self, **kwargs):
        super(TfuBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("tfu")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('a', val=[80,44.04074,31.48271,19.99465,8.95877,90.72782,27.45211,6.70369,2.7993,2.7993,80,44.04074,31.48271,19.99465,8.95877,90.72782,27.45211,6.70369,2.7993,2.7993,80,44.04074,31.48271,19.99465,8.95877,90.72782,27.45211,6.70369,2.7993,2.7993,4.09558,124.86209], desc='')
        self.add_input('b', val=[0.80,1.06207,0.78811,0.71253,0.68815,0.44422,0.44623,0.68041,0.91199,0.91199,0.80,1.06207,0.78811,0.71253,0.68815,0.44422,0.44623,0.68041,0.91199,0.91199,0.80,1.06207,0.78811,0.71253,0.68815,0.44422,0.44623,0.68041,0.91199,0.91199,0.96587,0.31031], desc='')
        self.add_input('Mass', val=[25,0,242.6,257,55,2450,0,326,0,0,15,0,312,53.8,10.9,490,0,120,0,0,30,90,45,0,33,0,0,0,0,0,15,20], desc='')

        self.add_output('TFU', val=1.0, desc='')



        