# -*- coding: utf-8 -*-
"""
  total.py generated by WhatsOpt 1.9.4
"""
import numpy as np
from development_cost.total_base import TotalBase

class Total(TotalBase):
    """ An OpenMDAO component to encapsulate Total discipline """
		
    def compute(self, inputs, outputs):
        """ Total computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
            Cp = inputs['Cp']
            f0 = inputs['f0'] 
            f1 = inputs['f1'] 
            f10 = inputs['f10']
            f11 = inputs['f11'] 
            f3 = inputs['f3']    
            MAIT = inputs['MAIT']
            PO = inputs['PO']

            Cdev = (Cp * (PO + MAIT)) * f0 * f1 * f3 * f10 * f11

            outputs['Cdev'] = Cdev
        return outputs   

# Reminder: inputs of compute()
#   
#       inputs['Cp'] -> shape: 1, type: Float    
#       inputs['f0'] -> shape: 1, type: Float    
#       inputs['f1'] -> shape: 1, type: Float    
#       inputs['f10'] -> shape: 1, type: Float    
#       inputs['f11'] -> shape: 1, type: Float    
#       inputs['f3'] -> shape: 1, type: Float    
#       inputs['MAIT'] -> shape: (32,), type: Float    
#       inputs['PO'] -> shape: (32,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(Total, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Total """
#   
#       	partials['Cdev', 'Cp'] = np.zeros((32, 1))
#       	partials['Cdev', 'f0'] = np.zeros((32, 1))
#       	partials['Cdev', 'f1'] = np.zeros((32, 1))
#       	partials['Cdev', 'f10'] = np.zeros((32, 1))
#       	partials['Cdev', 'f11'] = np.zeros((32, 1))
#       	partials['Cdev', 'f3'] = np.zeros((32, 1))
#       	partials['Cdev', 'MAIT'] = np.zeros((32, 32))
#       	partials['Cdev', 'PO'] = np.zeros((32, 32))        
